# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2019-03-20 15:12:20 -0700 by appacademy:
gem "rspec", "~> 3.8"
